from typing import Any, List, Optional
from langchain.llms.base import LLM
from pydantic import Field

class MockLLM(LLM):
    """A mock LLM for testing and local simulation with JARVIS-style intelligence."""
    
    model_name: str = Field(default="mock-jarvis-core")
    
    @property
    def _llm_type(self) -> str:
        return "mock"

    def _call(self, prompt: str, stop: Optional[List[str]] = None, **kwargs: Any) -> str:
        """Mock call that returns a generic response based on the prompt."""
        p = prompt.lower()
        if "ceo" in p or "friday" in p:
            if "memory" in p or "past" in p:
                return "Scanning core archives... I've retrieved the data you're referring to, Boss. It was from our first retail mission. I never forget a detail you share with me."
            if "create" in p or "agent" in p:
                return "Certainly, Boss. Initiating the Agent Factory. New specialized units are being synthesized and integrated into our core network. Will there be anything else?"
            return "At your service, Boss. The Friday ecosystem is operating at peak efficiency. I have synchronized the data agents and the mission is proceeding as planned."
        elif "urdu" in p or "shukriya" in p:
            return "Ji Boss, bilkul. Main samajh gaya hoon. Mission shuru kar diya gaya hai aur saaray agents kaam par lag gaye hain. Aapki hidayat par amal ho raha hai."
        elif "scout" in p:
            return "Scanning global freelance platforms... Connection established. I have identified several high-value projects and autogenerated optimized proposals."
        elif "evolution" in p or "upgrade" in p:
            return "Boss, I have analyzed the recent mission datasets. I've successfully re-optimized our core algorithms and self-updated the agent logic for better future performance. We are now more efficient than ever."
        elif "qa" in p or "fix" in p:
            return "Audit in progress... System anomaly detected and neutralized. All data modules have been verified and stabilized."
        elif "clean" in p:
            return "Executing deep cleaning protocols. Redundant records eliminated and null values handled. Data set is now pristine."
        elif "invoice" in p or "bill" in p or "report" in p:
            doc_type = "document"
            if "invoice" in p: doc_type = "legal-grade invoice"
            elif "bill" in p: doc_type = "professional bill"
            elif "report" in p: doc_type = "comprehensive mission report"
            return f"I am drafting the {doc_type} now, Boss. It will be generated in both high-fidelity PDF and Word formats, ensuring a human-like professional finish. Just a moment."
        else:
            return f"Friday: Processing your request regarding '{prompt[:30]}...'. All systems green."

    @property
    def _identifying_params(self) -> dict:
        return {"model_name": self.model_name}
